Use new app:update task to complete upgrade to Rails 7.2.0
    for service in books reviews users search signatures jwts
    do
        echo '==========' $service '=========='
        (
            cd $service
            bin/rails app:update
        )
    done

I had to edit `config/environments/development.rb` and `config/puma.rb`
so each service used its expected port instead of the default port `3000`.

!!!  BROKEN  !!!  BROKEN  !!!  BROKEN  !!!

Since the update to Rails `7.2.0`, the Rails apps are broken.  I haven't
anyone talking about it on the Web, yet.  When the API Gateway calls the
services for their service definition, they each fail with an error
message like the following:

```
Interface `Node` hidden because it has no visible implementers
undefined local variable or method `warden' for an instance of ApolloFederation::FederatedDocumentFromSchemaDefinition
/Users/jtessier/.gem/ruby/3.3.4/gems/apollo-federation-3.8.5/lib/apollo-federation/federated_document_from_schema_definition.rb:83:in `query_type?'
/Users/jtessier/.gem/ruby/3.3.4/gems/apollo-federation-3.8.5/lib/apollo-federation/federated_document_from_schema_definition.rb:71:in `block in build_type_definition_nodes'
/Users/jtessier/.gem/ruby/3.3.4/gems/apollo-federation-3.8.5/lib/apollo-federation/federated_document_from_schema_definition.rb:70:in `select'
/Users/jtessier/.gem/ruby/3.3.4/gems/apollo-federation-3.8.5/lib/apollo-federation/federated_document_from_schema_definition.rb:70:in `build_type_definition_nodes'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/language/document_from_schema_definition.rb:262:in `build_definition_nodes'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/language/document_from_schema_definition.rb:33:in `document'
/Users/jtessier/.gem/ruby/3.3.4/gems/apollo-federation-3.8.5/lib/apollo-federation/schema.rb:35:in `federation_sdl'
/Users/jtessier/.gem/ruby/3.3.4/gems/apollo-federation-3.8.5/lib/apollo-federation/service_field.rb:22:in `_service'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/schema/field.rb:717:in `public_send'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/schema/field.rb:717:in `block (2 levels) in resolve'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/schema/field.rb:849:in `with_extensions'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/schema/field.rb:686:in `block in resolve'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:751:in `minimal_after_lazy'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/query.rb:391:in `after_lazy'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/schema/field.rb:684:in `resolve'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:375:in `block (2 levels) in evaluate_selection_with_resolved_keyword_args'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/tracing/trace.rb:52:in `execute_field'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:374:in `block in evaluate_selection_with_resolved_keyword_args'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:696:in `call_method_on_directives'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:363:in `evaluate_selection_with_resolved_keyword_args'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:273:in `evaluate_selection'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:228:in `block (3 levels) in evaluate_selections'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:227:in `block (2 levels) in evaluate_selections'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:209:in `each'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:209:in `block in evaluate_selections'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:696:in `call_method_on_directives'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:206:in `evaluate_selections'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:96:in `block (3 levels) in run_eager'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:95:in `block (2 levels) in run_eager'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:116:in `each_gathered_selections'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:86:in `block in run_eager'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:696:in `call_method_on_directives'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter/runtime.rb:85:in `run_eager'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter.rb:71:in `block (4 levels) in run_all'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/tracing/trace.rb:44:in `execute_query'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter.rb:70:in `block (3 levels) in run_all'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter.rb:58:in `block (2 levels) in run_all'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter.rb:54:in `each'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter.rb:54:in `each_with_index'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter.rb:54:in `block in run_all'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/tracing/trace.rb:40:in `execute_multiplex'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/execution/interpreter.rb:38:in `run_all'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/schema.rb:1380:in `multiplex'
/Users/jtessier/.gem/ruby/3.3.4/gems/graphql-2.3.13/lib/graphql/schema.rb:1356:in `execute'
/Users/jtessier/book-reviews/rails_graphql_federation/books/app/controllers/graphql_controller.rb:16:in `execute'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_controller/metal/basic_implicit_render.rb:8:in `send_action'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/abstract_controller/base.rb:226:in `process_action'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_controller/metal/rendering.rb:193:in `process_action'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/abstract_controller/callbacks.rb:261:in `block in process_action'
/Users/jtessier/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:110:in `run_callbacks'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/abstract_controller/callbacks.rb:260:in `process_action'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_controller/metal/rescue.rb:27:in `process_action'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'
/Users/jtessier/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/notifications.rb:210:in `block in instrument'
/Users/jtessier/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/Users/jtessier/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/notifications.rb:210:in `instrument'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_controller/metal/instrumentation.rb:76:in `process_action'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/abstract_controller/base.rb:163:in `process'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_controller/metal.rb:252:in `dispatch'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_controller/metal.rb:335:in `dispatch'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/routing/route_set.rb:67:in `dispatch'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/routing/route_set.rb:50:in `serve'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/journey/router.rb:53:in `block in serve'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/journey/router.rb:126:in `each'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/journey/router.rb:126:in `find_routes'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/journey/router.rb:34:in `serve'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/routing/route_set.rb:896:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/rack-3.1.7/lib/rack/etag.rb:29:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/rack-3.1.7/lib/rack/conditional_get.rb:43:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/rack-3.1.7/lib/rack/head.rb:15:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
/Users/jtessier/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:101:in `run_callbacks'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/callbacks.rb:30:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/executor.rb:16:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/railties-7.2.0/lib/rails/rack/logger.rb:41:in `call_app'
/Users/jtessier/.gem/ruby/3.3.4/gems/railties-7.2.0/lib/rails/rack/logger.rb:29:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/request_id.rb:33:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/rack-3.1.7/lib/rack/runtime.rb:24:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/server_timing.rb:60:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/executor.rb:16:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/static.rb:27:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/rack-3.1.7/lib/rack/sendfile.rb:114:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/actionpack-7.2.0/lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/railties-7.2.0/lib/rails/engine.rb:535:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
/Users/jtessier/.gem/ruby/3.3.4/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
/Users/jtessier/.gem/ruby/3.3.4/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/Users/jtessier/.gem/ruby/3.3.4/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
/Users/jtessier/.gem/ruby/3.3.4/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
/Users/jtessier/.gem/ruby/3.3.4/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
/Users/jtessier/.gem/ruby/3.3.4/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
/Users/jtessier/.gem/ruby/3.3.4/gems/logging-2.4.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
Completed 500 Internal Server Error in 23ms (Views: 0.2ms | GC: 7.4ms)
```